# Generated by Django 5.1.5 on 2025-04-19 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logreport',
            name='analytics_l_status_56997b_idx',
        ),
        migrations.RenameField(
            model_name='logreport',
            old_name='country_name',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='logreport',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='logreport',
            name='raw_log',
        ),
        migrations.AddField(
            model_name='logreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logreport',
            name='raw_log_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='log_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='source_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='threat_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
