# Generated by Django 5.1.5 on 2025-04-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Threat',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
