# Generated by Django 5.1.5 on 2025-04-27 13:15

import ai_analytics.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analytics', '0001_initial'),
        ('threat_detection', '0003_threatanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aireportfeedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Report Feedback', 'verbose_name_plural': 'Report Feedback'},
        ),
        migrations.AlterField(
            model_name='aireport',
            name='cache_valid_until',
            field=models.DateTimeField(default=ai_analytics.models.get_cache_expiry),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='severity_filter',
            field=models.CharField(choices=[('all', 'All Severities'), ('high', 'High Severity'), ('medium', 'Medium Severity'), ('low', 'Low Severity')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='source_filter',
            field=models.CharField(choices=[('all', 'All Sources'), ('apache', 'Apache Logs'), ('mysql', 'MySQL Logs')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='aireport',
            name='tokens_used',
            field=models.IntegerField(default=0, validators=[ai_analytics.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='aireportfeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='aireportfeedback',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='aireport',
            index=models.Index(fields=['created_by'], name='ai_analytic_created_befb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='aireportfeedback',
            index=models.Index(fields=['report'], name='ai_analytic_report__0ea5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='aireportfeedback',
            index=models.Index(fields=['user'], name='ai_analytic_user_id_c28c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='aireportfeedback',
            index=models.Index(fields=['rating'], name='ai_analytic_rating_56dc5e_idx'),
        ),
    ]
