# Generated by Django 5.1.5 on 2025-03-31 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('apache_access', 'Apache Access Log'), ('apache_error', 'Apache Error Log'), ('mysql_general', 'MySQL General Log'), ('mysql_slow', 'MySQL Slow Query Log'), ('mysql_error', 'MySQL Error Log')], max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_parsed', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_ingestion.logsource')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('log_level', models.CharField(blank=True, max_length=20, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_size', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('suspicious', 'Suspicious'), ('attack', 'Attack')], default='normal', max_length=15)),
                ('normalized_data', models.JSONField()),
                ('raw_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='log_ingestion.rawlog')),
            ],
        ),
        migrations.CreateModel(
            name='LogFilePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('position', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_ingestion.logsource')),
            ],
            options={
                'unique_together': {('source', 'file_path')},
            },
        ),
    ]
