# Generated by Django 5.1.5 on 2025-04-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsource',
            name='kafka_topic',
            field=models.CharField(default='raw_logs', help_text='Kafka topic for log messages', max_length=100),
        ),
        migrations.AddField(
            model_name='logsource',
            name='use_filebeat',
            field=models.BooleanField(default=False, help_text='Use Filebeat for real-time collection'),
        ),
        migrations.AddField(
            model_name='parsedlog',
            name='analysis_time',
            field=models.DateTimeField(blank=True, help_text='When the log was analyzed', null=True),
        ),
        migrations.AddField(
            model_name='parsedlog',
            name='analyzed',
            field=models.BooleanField(default=False, help_text='Whether this log has been analyzed for threats'),
        ),
        migrations.AddField(
            model_name='parsedlog',
            name='source_type',
            field=models.CharField(blank=True, help_text='Type of log (apache, mysql, etc)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rawlog',
            name='processing_status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('error', 'Error')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='raw_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='log_ingestion.rawlog'),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('suspicious', 'Suspicious'), ('attack', 'Attack')], db_index=True, default='normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='parsedlog',
            index=models.Index(fields=['analyzed', 'timestamp'], name='log_ingesti_analyze_6a1b90_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedlog',
            index=models.Index(fields=['status', 'source_ip'], name='log_ingesti_status_02dc19_idx'),
        ),
        migrations.AddIndex(
            model_name='rawlog',
            index=models.Index(fields=['is_parsed', 'timestamp'], name='log_ingesti_is_pars_37061c_idx'),
        ),
        migrations.AddIndex(
            model_name='rawlog',
            index=models.Index(fields=['processing_status'], name='log_ingesti_process_c6e671_idx'),
        ),
    ]
