# Generated by Django 5.1.5 on 2025-04-20 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0002_logsource_kafka_topic_logsource_use_filebeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
