# Generated by Django 5.1.5 on 2025-05-03 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0003_alter_parsedlog_timestamp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parsedlog',
            name='log_ingesti_analyze_6a1b90_idx',
        ),
        migrations.RemoveIndex(
            model_name='parsedlog',
            name='log_ingesti_status_02dc19_idx',
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='analysis_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='normalized_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='raw_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_ingestion.rawlog'),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='source_type',
            field=models.CharField(blank=True, default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='parsedlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
