# Generated by Django 5.1.5 on 2025-05-06 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0004_remove_parsedlog_log_ingesti_analyze_6a1b90_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agent_type', models.CharField(choices=[('system', 'System Agent'), ('apache', 'Apache Agent'), ('mysql', 'MySQL Agent'), ('application', 'Application Agent'), ('security', 'Security Agent')], max_length=20)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('os_info', models.CharField(blank=True, max_length=255, null=True)),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_interval', models.IntegerField(default=30, help_text='Log collection interval in seconds')),
                ('heartbeat_interval', models.IntegerField(default=60, help_text='Heartbeat interval in seconds')),
                ('log_paths', models.TextField(blank=True, help_text='Paths to monitor for logs', null=True)),
                ('monitored_services', models.CharField(blank=True, max_length=255, null=True)),
                ('encryption_enabled', models.BooleanField(default=True)),
                ('compression_enabled', models.BooleanField(default=True)),
                ('logs_collected', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_check_in'],
                'indexes': [models.Index(fields=['status'], name='log_ingesti_status_c6bc0a_idx'), models.Index(fields=['agent_type'], name='log_ingesti_agent_t_d038b0_idx'), models.Index(fields=['last_check_in'], name='log_ingesti_last_ch_65a327_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentResourceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(help_text='CPU usage percentage (0-100)')),
                ('memory_usage', models.FloatField(help_text='Memory usage percentage (0-100)')),
                ('disk_usage', models.FloatField(help_text='Disk usage percentage (0-100)')),
                ('log_volume', models.FloatField(help_text='Log volume (percentage of allocated space)')),
                ('iops', models.FloatField(blank=True, help_text='IO operations per second', null=True)),
                ('network_in', models.FloatField(blank=True, help_text='Network inbound KB/s', null=True)),
                ('network_out', models.FloatField(blank=True, help_text='Network outbound KB/s', null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_metrics', to='log_ingestion.logagent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', 'timestamp'], name='log_ingesti_agent_i_4c94b3_idx'), models.Index(fields=['timestamp'], name='log_ingesti_timesta_f5cdef_idx')],
            },
        ),
    ]
