# Generated by Django 5.1.5 on 2025-05-10 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0005_logagent_agentresourcemetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetricsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric_type', models.CharField(choices=[('cpu', 'CPU Usage'), ('memory', 'Memory Usage'), ('disk', 'Disk Usage'), ('log_volume', 'Log Volume')], max_length=20)),
                ('value', models.FloatField(help_text='Current usage percentage (0-100)')),
                ('total_available', models.FloatField(blank=True, help_text='Total available resource (e.g., GB)', null=True)),
                ('used_amount', models.FloatField(blank=True, help_text='Amount currently in use (e.g., GB)', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional metric-specific details', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='log_ingesti_timesta_5aac01_idx'), models.Index(fields=['metric_type'], name='log_ingesti_metric__1e3de9_idx'), models.Index(fields=['metric_type', 'timestamp'], name='log_ingesti_metric__738620_idx')],
            },
        ),
    ]
