# Generated by Django 5.1.5 on 2025-05-17 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0006_systemmetricshistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsource',
            name='kafka_topic',
        ),
        migrations.RemoveField(
            model_name='logsource',
            name='use_filebeat',
        ),
        migrations.AddField(
            model_name='logsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logsource',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='source_type',
            field=models.CharField(max_length=50),
        ),
    ]
