# Generated by Django 5.1.5 on 2025-05-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0007_add_user_to_logsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsource',
            name='kafka_topic',
            field=models.CharField(default='raw_logs', help_text='Kafka topic for log messages', max_length=100),
        ),
        migrations.AddField(
            model_name='logsource',
            name='use_filebeat',
            field=models.BooleanField(default=False, help_text='Use Filebeat for real-time collection'),
        ),
    ]
