# Generated by Django 5.1.5 on 2025-05-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0008_add_user_to_logsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsource',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='logsource',
            name='user',
        ),
        migrations.AlterField(
            model_name='logsource',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='source_type',
            field=models.CharField(choices=[('apache_access', 'Apache Access Log'), ('apache_error', 'Apache Error Log'), ('mysql_general', 'MySQL General Log'), ('mysql_slow', 'MySQL Slow Query Log'), ('mysql_error', 'MySQL Error Log')], max_length=20),
        ),
    ]
