# Generated by Django 5.1.5 on 2025-05-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0010_add_user_to_logsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsource',
            name='user',
        ),
    ]
