# Generated by Django 5.1.5 on 2025-05-16 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userdevicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('apache_path', 'Apache Log Path'), ('mysql_path', 'MySQL Log Path'), ('system_path', 'System Log Path'), ('custom_path', 'Custom Log Path'), ('setting', 'System Setting')], max_length=30)),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('description', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reverted', 'Reverted')], default='active', max_length=20)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
