"""
Django settings for LogDetection project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p=!cn!1g!)pcbq4lur7^@418c%u8965k1gx=1l&v+t#0w=nc%4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'log_ingestion',
    'threat_detection',
    'incident_detection',
    'alerts',
    'reports',
    'authentication',
    'smtp_integration',
    'rest_framework',
    'siem',
    'frontend',
    'analytics',
    'ai_analytics',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'LogDetection.middleware.DebugMiddleware',
]

ROOT_URLCONF = 'LogDetection.urls'
import os

# Make sure this part of your settings includes the frontend directory
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'frontend'),  # Add this line
            BASE_DIR,  # Include the project root as well
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LogDetection.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'log_detection',  
        'USER': 'root',          
        'PASSWORD': '',           
        'HOST': 'localhost',      
        'PORT': '3306',           
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,  # Set to a lower value for simpler passwords
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'static',  # Updated path
]
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'  # Redirect to homepage after login
LOGOUT_REDIRECT_URL = '/login/'  # Redirect to login page after logout
SIGNUP_REDIRECT_URL = '/login/'  # Redirect to login page after signup

# Email settings for account verification (if needed)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Update with your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''  
EMAIL_HOST_PASSWORD = ''


# Threat Intelligence API keys - replace with your actual API keys
# ABUSEIPDB_API_KEY = 'your-api-key'
# VIRUSTOTAL_API_KEY = 'your-api-key'

# Mock data for testing without API keys
USE_MOCK_THREAT_INTELLIGENCE = True

# OpenRouter API Configuration
OPENROUTER_API_KEY = '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'
OPENROUTER_MODEL = 'openai/gpt-4o-mini'
OPENAI_MAX_TOKENS = 1000  # Max tokens for report generation (adjust for report length)
OPENAI_TEMPERATURE = 0.2  # Lower for more factual, higher for more creative

# AI Report Configuration
AI_REPORT_CACHE_HOURS = 24  # How long to cache reports before regenerating

# Site Configuration
SITE_NAME = 'Log Detection Platform'


