# Generated by Django 5.1.5 on 2025-04-03 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('intrusion', 'Intrusion Attempt'), ('malware', 'Malware Detection'), ('authentication', 'Authentication Failure'), ('anomaly', 'Anomalous Activity'), ('policy', 'Policy Violation')], max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='new', max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('affected_systems', models.TextField(blank=True, null=True)),
                ('mitre_tactics', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='alerts.alert')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
