# Generated by Django 5.1.5 on 2025-04-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertNote',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
