# Generated by Django 5.1.5 on 2025-04-15 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_auto_20250416_0014'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(choices=[('intrusion', 'Intrusion Attempt'), ('malware', 'Malware Detection'), ('authentication', 'Authentication Failure'), ('anomaly', 'Anomalous Activity'), ('policy', 'Policy Violation')], db_index=True, max_length=50)),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('affected_systems', models.TextField(blank=True, null=True)),
                ('mitre_tactics', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('raw_log_id', models.IntegerField(blank=True, help_text='Reference to original raw log', null=True)),
                ('parsed_log_id', models.IntegerField(blank=True, help_text='Reference to parsed log', null=True)),
                ('detection_time', models.FloatField(blank=True, help_text='Time taken to detect the alert in ms', null=True)),
                ('analysis_data', models.JSONField(blank=True, help_text='Additional analysis data', null=True)),
                ('is_analyzed', models.BooleanField(default=False, help_text='Whether this alert has been analyzed')),
                ('last_analyzed', models.DateTimeField(blank=True, help_text='When the alert was last analyzed', null=True)),
                ('related_alerts', models.ManyToManyField(blank=True, related_name='related_to', to='alerts.alert')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='alerts.alert')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['timestamp'], name='alerts_aler_timesta_c1e3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['type'], name='alerts_aler_type_56c7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['ip_address'], name='alerts_aler_ip_addr_b17b91_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnote',
            index=models.Index(fields=['timestamp'], name='alerts_aler_timesta_1bf320_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnote',
            index=models.Index(fields=['alert'], name='alerts_aler_alert_i_9db0f4_idx'),
        ),
    ]
