# Generated by Django 5.1.5 on 2025-04-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_emailalert_smtpconfiguration_alertnotification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertnotification',
            old_name='alert_id',
            new_name='threat_id',
        ),
    ]
