# Generated by Django 5.1.5 on 2025-05-12 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_rename_alert_id_alertnotification_threat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('failed', 'Failed')], max_length=20)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('push', 'Push Notification'), ('sms', 'SMS'), ('slack', 'Slack')], max_length=20)),
                ('alert_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['notification_type'], name='alerts_noti_notific_6bc9d7_idx'), models.Index(fields=['event_type'], name='alerts_noti_event_t_b7e556_idx'), models.Index(fields=['timestamp'], name='alerts_noti_timesta_575090_idx'), models.Index(fields=['user'], name='alerts_noti_user_id_f3612f_idx')],
            },
        ),
    ]
