# Generated by Django 5.1.5 on 2025-04-19 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siem', '0002_auto_20250416_0015'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_ip', models.GenericIPAddressField()),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.CharField(max_length=2048)),
                ('status_code', models.IntegerField()),
                ('bytes_sent', models.IntegerField()),
                ('referrer', models.URLField(blank=True, max_length=2048, null=True)),
                ('user_agent', models.CharField(max_length=256)),
                ('server_name', models.CharField(max_length=100)),
                ('request_time', models.FloatField(help_text='Request processing time in seconds')),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='siem_apache_timesta_96cd68_idx'), models.Index(fields=['status_code'], name='siem_apache_status__faf4d5_idx'), models.Index(fields=['client_ip'], name='siem_apache_client__cfa2ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='MySQLLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thread_id', models.IntegerField()),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Information'), ('NOTE', 'Note')], max_length=10)),
                ('subsystem', models.CharField(max_length=50)),
                ('error_code', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField()),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
                ('host', models.CharField(max_length=255)),
                ('query', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='siem_mysqll_timesta_adf244_idx'), models.Index(fields=['severity'], name='siem_mysqll_severit_2f7de0_idx'), models.Index(fields=['error_code'], name='siem_mysqll_error_c_11b541_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(choices=[('APACHE', 'Apache Alert'), ('MYSQL', 'MySQL Alert')], max_length=10)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('apache_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siem.apachelogentry')),
                ('mysql_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siem.mysqllogentry')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='siem_securi_created_b19f43_idx'), models.Index(fields=['alert_type'], name='siem_securi_alert_t_546a02_idx'), models.Index(fields=['severity'], name='siem_securi_severit_6c3634_idx')],
            },
        ),
    ]
