# Generated by Django 5.1.5 on 2025-04-16 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestion', '0002_logsource_kafka_topic_logsource_use_filebeat_and_more'),
        ('threat_detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionrule',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='detectionrule',
            old_name='mitre_technique',
            new_name='mitre_technique_id',
        ),
        migrations.RemoveField(
            model_name='detectionrule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='detectionrule',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='mitre_tactic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detectionrule',
            name='recommendation_template',
            field=models.TextField(blank=True, help_text='Template with {placeholders} for dynamic recommendations', null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='affected_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='mitre_tactic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectionrule',
            name='rule_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='detectionrule',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='threat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='parsed_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_ingestion.parsedlog'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threats', to='threat_detection.detectionrule'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='threat',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=15),
        ),
        migrations.AlterField(
            model_name='threat',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='detectionrule',
            index=models.Index(fields=['rule_type'], name='threat_dete_rule_ty_737b97_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionrule',
            index=models.Index(fields=['severity'], name='threat_dete_severit_0e17f3_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['created_at'], name='threat_dete_created_d34d30_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['severity', 'status'], name='threat_dete_severit_831c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['source_ip'], name='threat_dete_source__d2416c_idx'),
        ),
    ]
