# Generated by Django 5.1.5 on 2025-04-25 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_detection', '0002_rename_active_detectionrule_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('analyze', 'General Analysis'), ('explain', 'Explanation'), ('suggest', 'Suggested Solutions'), ('risk', 'Risk Assessment'), ('related', 'Related Threats')], default='analyze', max_length=20)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='threat_detection.threat')),
            ],
            options={
                'indexes': [models.Index(fields=['threat', 'analysis_type'], name='threat_dete_threat__541df4_idx'), models.Index(fields=['generated_at'], name='threat_dete_generat_c0afad_idx')],
                'unique_together': {('threat', 'analysis_type')},
            },
        ),
    ]
