# Generated by Django 5.1.5 on 2025-05-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_detection', '0003_threatanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('template', models.TextField()),
                ('system_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
